config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'summary/index'
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, :controllers => { :registrations => 'users'} ,controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  resources :user_steps
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!--<footer class="footer text-muted bg-light">
  <div class="container">
    <span>© <%= Date.today.year %> MTN</span>
    <ul class="list-inline mb-0 float-right">
      <li class="list-inline-item mr-3"><%= link_to "Terms", terms_path %></li>
      <li class="list-inline-item mr-3"><%= link_to "Privacy", privacy_path %></li>
    </ul>
  </div>
</footer> -->

app/views/shared/_head.html.erb
<%if user_signed_in?%>
<title>Dashboard</title>
<% else %>
    <title>Students Tech Application. </title>
<% end %>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.9/css/mdb.min.css" rel="stylesheet">
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.9/js/mdb.min.js"></script>

<style media="screen">
.navbar.navbar-dark .breadcrumb .nav-item .nav-link, .navbar.navbar-light .navbar-nav .nav-item .nav-link {
    color: #fff !important;
    -webkit-transition: .35s;
    -o-transition: .35s;
    transition: .35s;
}

</style>

app/views/shared/_logo.html.erb
<%=image_tag('http://www.mozambique.co.za/images/mozambique-national-flag-590x390.png', width:'80px', height:'auto')%>

app/views/shared/_nav_scroller.html.erb
<%if user_signed_in?%>
<div class="nav-scroller bg-white box-shadow">
  <nav class="nav nav-underline">
    <a class="nav-link active" href="/">Dashboard</a>
    <a class="nav-link" href="#">
      Data
      <span class="badge badge-pill bg-light align-text-bottom">26mb</span>
    </a>

    <a class="nav-link" href="#">
      Voice
      <span class="badge badge-pill bg-light align-text-bottom">0mins</span>
    </a>

    <a class="nav-link" href="#">
      SMS
      <span class="badge badge-pill bg-light align-text-bottom">1</span>
    </a>

    <a class="nav-link" href="#">
    <%=render'shared/translator'%>
    </a>
  </nav>
</div>
<%end%>

app/views/shared/_navbar.html.erb
<% if user_masquerade? %>
  <div class="alert alert-warning text-center">
    You're logged in as <b><%= current_user.name %> (<%= current_user.email %>)</b>
    <%= link_to back_masquerade_path(current_user) do %><%= icon("times") %> Logout <% end %>
  </div>
<% end %>

<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand Header-item Header-logo"  do %>
      <%=render'shared/logo'%>  <span style="color:#fff">Student Tech </span>
    <%end%>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
      </ul>

      <ul class="navbar-nav">
        <li class="nav-item"><%= link_to "What's New", announcements_path, class: "nav-link #{unread_announcements(current_user)}" %></li>

        <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to notifications_path, class: "nav-link" do %>
            <span><i class="fa fa-bell" aria-hidden="true"></i></span>
          <% end %>
         </li>
         <li class="nav-item"> <a  class="nav-link" style="cursor:pointer" onclick="openNav()">&#9776; </a></li>

          <li class="nav-item dropdown">
            <%= link_to root_path, id: "navbar-dropdown", class: "nav-link dropdown-toggle", data: { toggle: "dropdown" }, aria: { haspopup: true, expanded: false } do %>
              <%= image_tag gravatar_image_url(current_user.email, size: 40), height: 20, width: 20, class: "rounded" %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
              <% if current_user.admin? %>
                <%= link_to "Admin Area", admin_root_path, class: "dropdown-item" %>
              <% end %>
              <%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>
          <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<%=render'shared/nav_scroller'%>

app/views/shared/_notices.html.erb
  <% flash.each do |msg_type, message| %>
    <div class="alert alert-info %>">
      <div class="container-fluid">
        <button class="close" data-dismiss="alert"><span>×</span></button>
        <%= message %>
      </div>
    </div>
  <% end %>

app/views/shared/_side_nav.html.erb
<div id="mySidenav" class="sidenav">
  <div class="row">
    <div class="col-md-12 ">
      <div class="img-responsive rounded2 ">
        <%=render'shared/logo'%>
      </div>
    </div>
  </div>

  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a> <br>
  <a href="#"><i class="fa fa-home" aria-hidden="true"></i>Dashboard</a>
  <a href="#"><i class="fa fa-lightbulb-o" aria-hidden="true"></i> Products</a>
  <a href="#"><i class="fa fa-file-text-o" aria-hidden="true"></i> Accounts</a>
  <a href="#"><i class="fa fa-question-circle" aria-hidden="true"></i> Get Help</a>
  <a href="#"><i class="fa fa-user-circle-o" aria-hidden="true"></i> Track</a>
</div>

app/views/shared/_translator.html.erb
<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', includedLanguages: 'pt', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>